package org.drad.movie_tickets.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class SpringDocConfiguration {

    @Bean
    OpenAPI apiInfo() {
        return new OpenAPI()
              .info(
                    new Info()
                          .title("Movie tickets")
                          .description(
                                "No description provided (generated by Openapi Generator https://github"
                                      + ".com/openapitools/openapi-generator)")
                          .contact(
                                new Contact()
                                      .email("daniel.ionut.rad@gmail.com")
                          )
                          .version("1.0.0")
              )
              ;
    }
}